# Read dataset

In [1]:
pip install keras

Requirement already satisfied: keras in c:\users\pawan\anaconda3\envs\deep_learning\lib\site-packages (2.8.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from warnings import filterwarnings
filterwarnings("ignore")

import pandas as pd
A = pd.read_csv("C:/Users/Pawan/Downloads/50_Startups.csv")

In [3]:
A.head()

         RND      ADMIN        MKT       STATE     PROFIT
0  165349.20  136897.80  471784.10    New York  192261.83
1  162597.70  151377.59  443898.53  California  191792.06
2  153441.51  101145.55  407934.54     Florida  191050.39
3  144372.41  118671.85  383199.62    New York  182901.99
4  142107.34   91391.77  366168.42     Florida  166187.94

# Define Y and X

In [4]:
Y = A[["PROFIT"]]
X = A.drop(labels=["PROFIT"],axis=1)

# Preprocessing

In [5]:
from PM8_weekend import preprocessing,replacer
replacer(A)
Xnew = preprocessing(X)

In [6]:
Xnew

,RND,ADMIN,MKT,STATE_California,STATE_Florida,STATE_New York
0,2.016411,0.560753,2.153943,0,0,1
1,1.955860,1.082807,1.923600,1,0,0
2,1.754364,-0.728257,1.626528,0,1,0
3,1.554784,-0.096365,1.422210,0,0,1
4,1.504937,-1.079919,1.281528,0,1,0
5,1.279800,-0.776239,1.254210,0,0,1
6,1.340066,0.932147,-0.688150,1,0,0
7,1.245057,0.871980,0.932186,0,1,0
8,1.030369,0.986952,0.830887,0,0,1
9,1.091819,-0.456640,0.776107,1,0,0
10,0.620398,-0.387599,0.149807,0,1,0
11,0.593085,-1.065540,0.319834,1,0,0
12,0.443260,0.215449,0.320617,0,1,0
13,0.402078,0.510179,0.343957,1,0,0
14,1.017181,1.269199,0.375742,0,1,0
15,0.897913,0.045868,0.419219,0,0,1
16,0.094441,0.009118,0.440446,1,0,0
17,0.460720,0.855666,0.591017,0,0,1
18,0.396725,-0.258465,0.692992,0,1,0
19,0.279442,1.159837,-1.743127,0,0,1
20,0.055726,-0.269588,0.723926,1,0,0
21,0.102724,1.169186,0.732788,0,0,1
22,0.006007,0.051850,0.762376,0,1,0
23,-0.136201,-0.562211,0.774349,0,1,0
24,0.073115,-0.795469,-0.581939,0,0,1
25,-0.199312,0.656489,-0.603517,1,0,0
26,0.035370,0.821718,-0.635835,0,1,0
27,-0.035519,0.235069,1.174271,0,0,1
28,-0.168793,2.210141,-0.767189,0,1,0
29,-0.178609,1.142457,-0.858134,0,0,1
30,-0.258074,-0.205629,-0.990357,0,1,0
31,-0.276958,1.130554,-1.014419,0,0,1
32,-0.226949,0.283924,-1.362450,1,0,0
33,-0.401129,-0.659324,0.029817,0,1,0
34,-0.600682,1.310535,-0.001879,1,0,0
35,-0.609750,-1.308658,-0.045493,0,0,1
36,-0.991570,0.205925,-0.081763,0,1,0
37,-0.652532,-2.525994,-0.115608,1,0,0
38,-1.177178,-1.997270,-0.212785,0,0,1
39,-0.773820,-1.383122,-0.297583,1,0,0
40,-0.989577,-0.100900,-0.315786,1,0,0
41,-1.008534,-1.320796,-0.384552,0,1,0
42,-1.102106,-0.906938,-0.520596,1,0,0
43,-1.281134,0.217682,-1.449605,0,0,1
44,-1.134305,1.206419,-1.509074,1,0,0
45,-1.600350,0.101254,-1.727400,0,0,1
46,-1.593413,-0.199322,0.711122,0,1,0
47,-1.622362,0.507722,-1.743127,1,0,0
48,-1.610433,-2.509409,-1.743127,0,0,1
49,-1.622362,-0.157226,-1.369985,1,0,0

# Divide Data in training and testing set

In [7]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(Xnew,Y,test_size=0.2,random_state=23)

# Create a NN

In [8]:
from sklearn.neural_network import MLPRegressor
mlpr = MLPRegressor(hidden_layer_sizes=(100,100,100),random_state=21)
nn = mlpr.fit(xtrain,ytrain)
pred_ts = nn.predict(xtest)
pred_tr = nn.predict(xtrain)

from sklearn.metrics import mean_squared_error
ts_err = mean_squared_error(ytest,pred_ts)
tr_err = mean_squared_error(ytrain,pred_tr)

In [9]:
ts_err

10064244940.947903

In [10]:
tr_err

9677924325.231045

In [11]:
from numpy import sqrt
sqrt(tr_err)

98376.4419219919

In [12]:
sqrt(ts_err)

100320.71042884367

How many hidden layers size of each hidden layers (HYPERPARAMETER)

In [13]:
from keras.models import Sequential